DROP TABLE IF EXISTS users, items, bookings, comments;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    description  VARCHAR(2000),
    is_available BOOLEAN,
    owner        BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    request_id   BIGINT
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_time   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    booker_id  BIGINT                      NOT NULL REFERENCES users (id),
    item_id    BIGINT                      NOT NULL REFERENCES items (id),
    status     VARCHAR(20)                 NOT NULL
);

CREATE TABLE IF NOT EXISTS comments
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text    VARCHAR(2000)               NOT NULL,
    item_id BIGINT                      NOT NULL REFERENCES items (id),
    user_id BIGINT                      NOT NULL REFERENCES users (id),
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL
);